services:
  postgres:
    container_name: my-postgres-container
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5434:5432

volumes:
  pgdata:
