services:
  postgres:
    container_name: my-postgres-container
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  pgdata:
